### ISSUE TITLE
Possible cc3d Performance Improvements

### ISSUE THREAD

**Issue by william-silversmith** [linleon1995/Nodule_Detection#1]
Hi! I was just browsing projects using cc3d and noticed you're using it a lot! Thank you! I don't know if this is important to your project or not but I just wanted to point out a few tricks you can use since often iterating over many objects can be expensive.

For example, this code could be improved using cc3d library features.

https://github.com/linleon1995/detectron2-mask-rcnn/blob/cfab721d26af73a85c926d260e8870c8a9369b4a/data/data_utils.py#L108-L116

```python
def split_individual_mask(mask):
    ccl_mask, N = cc3d.connected_components(mask, connectivity=8, return_N=True)
    if N <= 1:
       return [ mask ]
    return [ label_mask for label, label_mask in cc3d.each(ccl_mask, binary=True, in_place=False) ]
```

Here's another piece of code that could be improved:

https://github.com/linleon1995/detectron2-mask-rcnn/blob/50b2d4f2e750b4ff81804ff2ad0fe2891155c3f9/Liwei/FTP1m_test/util.py#L198-L209

```python
                        lab_img, N = cc3d.connected_components(hu_mask, return_N=True)
                        if N > 1:
                            stats = cc3d.statistics(lab_img)
                            for i in range(1,N):
                                coord_irc = stats[i]['centroid']
                                xyz = irc2xyz(coord_irc, origin_xyz, vxSize_xyz, direction_a)
                                series_uid = raw_path.split('\\')[-1][:-4]  # windows是'\\' ubuntu是'/'
                                dict_.append([case, series_uid, raw_path, mask_path, xyz[0], xyz[1], xyz[2]])
```

I haven't tested these snippets, but they should give you the general idea. I anticipate that they should be much faster. There are a few other areas in the code where similar techniques would apply. I hope this is helpful! Please feel free to ignore this if it would be a waste of your time.

Will

**Comment by linleon1995** [comment]
Hi, sorry for the late reply. All the code pieces that you provided look useful. I will try it later. Thanks.
